In [2]:
import numpy as np

In [6]:
# creating an array


a=np.array([1,2,4,5,6])
a

array([1, 2, 4, 5, 6])

In [7]:
a.ndim  # checking dimension

1

In [8]:
aa=np.array([[1,2,4],[7,8,9]])
aa                                  # two dimensional array

array([[1, 2, 4],
       [7, 8, 9]])

In [9]:
aa.ndim

2

In [12]:
## create a three 3 dimensional array

aaa=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
aaa

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [13]:
aaa.ndim

3

## Zero's & One's 

In [14]:
var=np.zeros(10)

In [15]:
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
var1=np.ones(5)

In [17]:
var1

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [19]:
np.zeros((2,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## functions

In [11]:
var=np.array([22,156,78,15])
var

array([ 22, 156,  78,  15])

In [4]:
type(var)

numpy.ndarray

In [41]:
var.argmax()   # max value in index position

1

In [42]:
var.argmin()

3

In [43]:
var[0]

22

In [44]:
var[3]

15

In [45]:
var[1]

156

In [7]:
var

array([ 22, 156,  78,  15])

In [46]:
var[0:2]

array([ 22, 156])

In [48]:
var[1:3]

array([156,  78])

In [12]:
var[1:-1]

array([156,  78])

In [50]:
arr=np.array([1,2,3,4,5,6.1,8])
arr

array([1. , 2. , 3. , 4. , 5. , 6.1, 8. ])

In [51]:
arr.dtype

dtype('float64')

In [52]:
arr.size

7

In [ ]:
## create a numpy array with size 5,and  dataype of string

In [53]:
a=np.array(['a','b','c','d','e'])
a

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [55]:
a.dtype

dtype('<U1')

In [56]:
s=np.array(["str1","str2","str3","str4","str5"])
s


array(['str1', 'str2', 'str3', 'str4', 'str5'], dtype='<U4')

In [57]:
s=np.array(['a','e','i','o','u'])
s

array(['a', 'e', 'i', 'o', 'u'], dtype='<U1')

In [58]:
arr=np.array(["ab","cd","ed","hh","iy"])
arr

array(['ab', 'cd', 'ed', 'hh', 'iy'], dtype='<U2')

In [59]:
arr.dtype

dtype('<U2')

In [60]:
## create a numpy array with size 5,and  dataype of float

In [61]:
a1=np.array([1.2,4,3,7,6])
a1

array([1.2, 4. , 3. , 7. , 6. ])

In [63]:
a1.dtype

dtype('float64')

In [ ]:
# create two dimensional array
# four arrays in the external arrays
# it should have two elements each

In [71]:
a=np.array([[1,2],[3,4],[5,6],[7,8]])
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [65]:
a.ndim

2

In [66]:
x=np.array([2,4,6,8])

In [67]:
x

array([2, 4, 6, 8])

In [68]:
np.sqrt(x)

array([1.41421356, 2.        , 2.44948974, 2.82842712])

In [69]:
np.log(x)

array([0.69314718, 1.38629436, 1.79175947, 2.07944154])

In [72]:
a=np.array([[1,2],[3,4],[5,6],[7,8]])
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [73]:
a.shape

(4, 2)

## Transpose

In [74]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [75]:
a.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

## Floor & Ceil

In [82]:
arr2=np.array([10.2,3.1,4.2,7.1,8.9,7])
arr2

array([10.2,  3.1,  4.2,  7.1,  8.9,  7. ])

In [83]:
np.floor(arr2)

array([10.,  3.,  4.,  7.,  8.,  7.])

In [84]:
np.ceil(arr2)

array([11.,  4.,  5.,  8.,  9.,  7.])

In [85]:
np.round(arr2)

array([10.,  3.,  4.,  7.,  9.,  7.])

In [86]:
a1=np.array([[ 1, 27.96426291, 1.73205081,  2,  2.23606798, 2.44948974]])
a1

array([[ 1.        , 27.96426291,  1.73205081,  2.        ,  2.23606798,
         2.44948974]])

In [87]:
np.ceil(a1)

array([[ 1., 28.,  2.,  2.,  3.,  3.]])

## Stacking

In [88]:
import numpy as np
arr23=np.arange(10).reshape(2,5)
arr24=np.arange(20).reshape(4,5)

In [89]:
arr23

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [90]:
arr24

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [91]:
np.vstack((arr23,arr24))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [92]:
np.hstack((arr23,arr24))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

- ## for v stack (vertical) number of columns should be same for both arrays, and for the hstack(horizondal) the number of rows should be equal for two arrays

In [93]:
arr23=np.arange(10).reshape(5,2)
arr24=np.arange(20).reshape(5,4)

In [96]:
arr23

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [97]:
arr24

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [94]:
np.hstack((arr23,arr24))

array([[ 0,  1,  0,  1,  2,  3],
       [ 2,  3,  4,  5,  6,  7],
       [ 4,  5,  8,  9, 10, 11],
       [ 6,  7, 12, 13, 14, 15],
       [ 8,  9, 16, 17, 18, 19]])

## numpy split

In [98]:
arr28=np.arange(100).reshape(10,10)

In [99]:
arr28

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [101]:
np.vsplit(arr28,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [102]:
np.hsplit(arr28,2)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]